### ISSUE TITLE
Enable basic html formatting in content descriptor

### ISSUE THREAD

**Issue by Popolechien** [openzim/overview#11]
copy/paste from [zimfarm/719](../../zimfarm/issues/719)

Some of our zim files have fairly long descriptions and we end up with a block of text. It would be convenient if in the Description field of recipes we could insert some basic HTML (e.g. <br/>) so as to render this text in a more palatable format

![Capture d’écran 2022-09-23 à 14 41 09](https://user-images.githubusercontent.com/21675885/191994091-935725aa-3885-473f-941c-9b25f3794c80.png)

**Comment by kelson42** [comment]
My two cents.

We have currently a "Description" which should a "short sentence" but actually people put what should be in "LongDescription" wrongly in it. 

This is mostly the fault of scrapers/zimfarm/readers which don't support "LongDescription" metadata.

Actually, the kiwix-serve welcone page should not have anyway so much texy displayed like this anyway. But that does not invalidate this ticket probably.

That said IMO, just allowing carriage returns in the LongDescription metadata might be good enough.

Allowing HTML would bring following problems:
* non homogenous descriptions with different fonts, color, etc
* problems with non-html renderer like in ios, macos, linux, windows, android...
* big security challenges around javascript/css

**Comment by kelson42** [comment]
One of the first things I want to do to handle the problem reported here is to clarify usage around metadata `Title`, `Description` and `LongDescription`. See https://wiki.openzim.org/wiki/Metadata

... and first given recommend max size. Here are the value on Google Play Store for the same Medata:
![image](https://user-images.githubusercontent.com/1029718/193425073-e4b6f118-0433-4d58-bf8a-65db0b819e96.png)

@mgautierfr @Popolechien @mgautierfr Would we agree to take the three of them for our medata?

**Comment by rgaudin** [comment]
Good ; once this is all cleared-up, we'll be able to add support for it in the scrapers and the zimfarm

**Comment by Popolechien** [comment]
Yup. May want to increase the first one to 50 characters as we have quite a few zim titles that also include the series (e.g. ``Basic Concepts of Chemistry (Grade 11 Chemistry``) which has 48 char.)

**Comment by mgautierfr** [comment]
Agree with @kelson42 proposition.

On extended the name to 50 chars, it raises the question of how such a long title is displayed.
On library.kiwix.org, I've found `Basic economics concepts | AP Macroeconomics | Khan Academy` which is 59 chars.
It is displayed on 3 lines. Limiting on the first 50 chars allow it to be displayed on 2 lines and the 30 first chars are display on one line.

If we have a clear distinction between short description and long description both long title could be split in title and short description:
- `Basic Concepts of Chemistry (Grade 11 Chemistry)` => `Basic Concepts of Chemistry` and `Grade 11 Chemistry`
- `Basic economics concepts | AP Macroeconomics | Khan Academy` => `Basic economics concepts` and `AP Macroeconomics | Khan Academy` (and I think that Khan Academy should go in other metadata as Author)

Both title are less than 30 chars (27 and 24)

I think limiting title length force us to write clearer title/description and it would be better for the user.

**Comment by kelson42** [comment]
I will go forward with this, 50 characters for the title seems too long and can not be displayed properly. ZIM content creator will have to be imaginative about how to short titles.

**Comment by kelson42** [comment]
Specification [updated](https://wiki.openzim.org/w/index.php?title=Metadata&action=history)

**Comment by kelson42** [comment]
I close this ticket. Spec has been updated and most of the tooling as well. We shoukd have homogenous ZIM metadata now (at list for title, description and Longdescription).
