### ISSUE TITLE
Needing soon hard token for code signing

### ISSUE THREAD

**Issue by kelson42** [openzim/overview#12]
https://knowledge.digicert.com/generalinformation/new-private-key-storage-requirement-for-standard-code-signing-certificates-november-2022.html

I guess this will mean we have to move to a cloud code signing solution. For example https://www.ssl.com/esigner/ (https://github.com/electron-userland/electron-builder/issues/6158)

https://www.ssl.com/how-to/cloud-code-signing-integration-with-github-actions/

**Comment by kelson42** [comment]
https://shop.certum.eu/open-source-code-signing-on-simplysign.html

**Comment by rgaudin** [comment]
Not sure what this is doing in openZIM. obsolete anyway
