### ISSUE TITLE
Vuex is not anymore the standard Vue state management library

### ISSUE THREAD

**Issue by benoit74** [openzim/overview#20]
In our standard stack, we previously decided to use Vuex for state management: https://github.com/openzim/overview/wiki/openZIM-workflow#frontend

This is not anymore the official state management management library : https://vuex.vuejs.org/

![image](https://github.com/openzim/overview/assets/7102089/5c25b0f5-c050-4f9c-8053-8198772448c3)

I recommend to adapt our standard to use Pinia instead of Vuex, so that new projects (including offspot/metrics frontend) use this new Vue official library.

**Comment by rgaudin** [comment]
Indeed we chose it for nautilus-webui but did not update the doc

**Comment by benoit74** [comment]
Done
