### ISSUE TITLE
Comparing .slob (aard2) and .zim (kiwix) Wiktionaries

### ISSUE THREAD

**Issue by Popolechien** [openzim/overview#32]
I'm currently looking at the French wiktionary on both Kiwix and Aard2. 

Comparing both versions of the same wiktionaries, I see that display is the same. 
Aard2           |  Kiwix
:-------------------------:|:-------------------------:
<img src="https://github.com/openzim/overview/assets/21675885/ecd22c4a-cb83-41b1-a43e-1d2991a9be77" width="300"/> | <img src="https://github.com/openzim/overview/assets/21675885/f50138f5-d82d-426a-8077-54b3345f3d94" width="300"/>

Pretty identical if you ask me.

Going further down, it looks like the app even has embedded reader for sounds:
Aard2           |  Kiwix
:-------------------------:|:-------------------------:
<img src="https://github.com/openzim/overview/assets/21675885/55cebee2-7b46-4e8e-a1ab-aeecd2a4c0ad" width="300"/>  |  <img src="https://github.com/openzim/overview/assets/21675885/a9c7f8a3-1944-4c15-a4ae-a3b449504277" width="300"/>

Search results appear different, but nothing major as far as I can tell
Aard2           |  Kiwix
:-------------------------:|:-------------------------:
<img src="https://github.com/openzim/overview/assets/21675885/8efff99a-a912-4985-a1bb-6a295555bd55" width="300"/> | <img src="https://github.com/openzim/overview/assets/21675885/bde88900-35aa-46af-88ea-7f1ab5363dde" width="300"/>

The zim file is 4.6GB while the .slob is only 829MB. The slob file does not host images (they just disappear if one is fully offline), but even then the `nopic` zim only goes down to 4.1GB. I also understand that slob is not fully index, but even then that does not explain the huge difference in size. 

So my questions at this stage are:
- why is the same file 5 times bigger as a zim as it is as a slob?
- could kiwix eventually read .slob files?

**Comment by mgautierfr** [comment]
- Xapian fulltext index is 1.79GB.
- Xapian title index is 0,69GB.
- Zim (without images) has more entries (115592 more) (lot of svg), difficult to know the mean size of the item, but random picking in them show img between 1KB and 10KB. With a mean of 5KB we have 0,5GB.

With this only, we have 3GB. Removing them would reduce the zim size from 4,1GB to 1,04GB
We still have some minor improvement (No title saved, size of "dirent structure" (9bytes per entry), only one way to compress (so 1 byte per cluster), ...) and we have something pretty equivalent.
