### ISSUE TITLE
Handling of .h5p files

### ISSUE THREAD

**Issue by Popolechien** [openzim/overview#34]
.h5p files are pretty popular within the Open Education Community. Kolibri is apparently working on being able to read those, but I have no additional info than "it's in development". Would handling these file need to be done via a dedicated scraper, or is it more of a feature to be implemented as part of Nautilus, for instance?

**Comment by rgaudin** [comment]
It's been a Kolibri KIND for a long time ; at least since we created kolibri2zim but it seemed to be a wish and not actually implemented.

See https://github.com/openzim/kolibri/issues/1
