### ISSUE TITLE
Develop a graphical ZIM explorer

### ISSUE THREAD

**Issue by benoit74** [openzim/overview#37]
While checking ZIM quality or diagnosing issues, the QA team often needs to:
- look at the list of entries of a given ZIM
- search for a specific text or patterns in this list (and count entries, get total size in ZIM)
- get details (mainly size) of a given entry and observe content (when its text)
- get list of duplicated entries

This is especially important for Zimit ZIMs where the ZIM content is way less predicatable than other scrapers.

While as a developer I do this with a combination of zimcheck / zimdump / grep / wc / ..., this is not possible for the rest of the content team and this is not convenient at all for me, consuming too much of my time.

Should we develop a graphical ZIM explorer?

@RavanJAltaie @Popolechien does it make any sense for you? Do you wanna add more?

**Comment by Popolechien** [comment]
That is a good question. Feels like this would be needed, but I also suspect the tool would still be too complex for us to use as we wouldn't know what it is we're looking for in a zim.
Other than that, isn't there a bit of overlap with the CMS (or couldn't some of the features you mention be integrated into it)?

**Comment by rgaudin** [comment]
- I still believe training a couple people to use a few tools would be a better way.
- there is indeed overlap with the CMS but CMS is a (to-be) publication & QA tool. I can see use cases that it wont cover in your workflow.
- a good part of the needs is available via fuse module. Maybe packaging it properly for windows would help

**Comment by mgautierfr** [comment]
> a good part of the needs is available via fuse module. Maybe packaging it properly for windows would help

I may have miss something. But we have that ?

**Comment by rgaudin** [comment]
> I may have miss something. But we have that ?

I though you had someone working on one…

**Comment by mgautierfr** [comment]
We have this https://github.com/openzim/zim-tools/pull/400
But I don't know if juzz0 is actually working on it.

**Comment by kelson42** [comment]
Definitly a ticket for ZIM tools, I would recommend to amake on ticket per question. Current tools should be able to do the job. If people can not use the command line and follow a howto and are not a fit to diagnose anything for a broken ZIM IMHO. ZIM fuse might be indeed part of the response, but this is Linux only.

**Comment by rgaudin** [comment]
> ZIM fuse might be indeed part of the response, but this is Linux only.

It's not ; via third party tools which is why I mentioned packaging. Not sure setup can be simplified enough though.

**Comment by rgaudin** [comment]
For some reason I read _Desktop_ while it's not written anywhere 😅
