### ISSUE TITLE
Should we add `[REGRESSION]` to all regression bugs?

### ISSUE THREAD

**Issue by benoit74** [openzim/overview#43]
@kelson42, I see that you are regularly setting a `[REGRESSION]` prefix to titles of issues which are a regressions, and you're regularly modifying issues titles to add this prefix when it was missing (like https://github.com/openzim/youtube/issues/369). This hence seems something particularly important to do for you. I however see no mention of it in our guidelines, e.g. https://github.com/openzim/overview/wiki/openZIM-code-contribution-workflow.

Is it something you would like to see as a standard in all our repos?

I'm personally strongly against this practice for multiple reasons:
- the use of capital letters and brackets make it very very aggressive ; while I understand it might be more or less personal feeling, it is widely accepted on the Internet that all capital letters is meaning something that is shouted out
- being shouted on me when I'm already facing a bug (which is not something I appreciate to face on a personal basis) is only adding more stress and discomfort ... not something useful at all
- we already have tags to filter / characterize issues, and I don't think that adding a prefix in issue title helps a lot for filtering (we could add a "regression" tag if "bug" is not sufficient
- on that, mostly all issues labelled "bug" are regression in scrapers ; other issues are labelled "enhancement". It is rare to have a "bug" which is not a regression, since we usually consider that either it was working before, and it is a bug, or it was never working like that, and it is an enhancement needed

I hence recommend to:
- avoid putting anything in all capital letters or inside brackets in issues title
- avoid putting any prefix tag(s) in issues title, prefer to use labels instead

**Comment by rgaudin** [comment]
I share this completely.

**Comment by benoit74** [comment]
I'm aligned with the wiki changes, all good for me.

Regarding the sensitivity to regressions ... the most successful process I've found so far is investing in automated tests, ideally capable to run at the PR level or at least once a day, so that it is ideally catch before merge, at least before release. And I've witnessed we have lot of potential for progress on this process.

**Comment by rgaudin** [comment]
It's assumed but written nowhere that regressions affect released version.

I believe this is answered
